# Generated by Django 4.2.3 on 2023-07-13 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, choices=[('mal', 'Мужской'), ('fem', 'Женский')], max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('metro_station', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, choices=[('mal', 'Мужской'), ('fem', 'Женский')], max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('metro_station', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('act', 'Действующий'), ('ina', 'Недействующий')], max_length=3)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('delivery_method', models.CharField(choices=[('pick', 'Самовывоз'), ('deli', 'Доставка')], max_length=4)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Банковской картой')], max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proc', 'В работе'), ('done', 'Выполнено')], max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('text', models.TextField()),
                ('date_in', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('bis', 'Бисквитные'), ('san', 'Песочные'), ('puf', 'Слоеные'), ('waf', 'Вафельные'), ('air', 'Воздушные'), ('tin', 'Крошковые'), ('cus', 'Заварные')], max_length=3)),
                ('weight', models.IntegerField(blank=True)),
                ('best_before_date', models.IntegerField(blank=True)),
                ('storage_temperature', models.IntegerField(blank=True)),
                ('proteins', models.IntegerField(blank=True)),
                ('fats', models.IntegerField(blank=True)),
                ('carbohydrates', models.IntegerField(blank=True)),
                ('energy_value', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('category', models.ManyToManyField(related_name='products', to='main.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.product'),
        ),
        migrations.CreateModel(
            name='ManufacturerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, choices=[('mal', 'Мужской'), ('fem', 'Женский')], max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturermanagers', to='main.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('data', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='main.company'),
        ),
    ]
